#!/bin/bash

echo "🔧 Создание скрипта для исправления проекта Xcode"
echo ""
echo "Этот скрипт поможет исправить проблемы с проектом."
echo ""
echo "Проблемы:"
echo "1. Info.plist дублируется в Copy Bundle Resources"
echo "2. Proto файлы пытаются компилироваться"
echo ""
echo "Решение:"
echo "1. Откройте проект в Xcode"
echo "2. Следуйте инструкциям в FIX_XCODE_ISSUES.md"
echo ""
echo "Или выполните вручную:"
echo ""
echo "Для Info.plist:"
echo "  - Build Phases → Copy Bundle Resources → удалите Info.plist"
echo ""
echo "Для proto файлов:"
echo "  - Выберите папку Proto/ → File Inspector → Target Membership → снимите галочку"
